name: drop_drying
channels:
  - conda-forge
  - nodefaults
dependencies:
  - libMobility
  - numpy
  - stochasticHydroTools::RigidBodyLight
  - matplotlib
  - superpunto
  - scipy
  - pyamg
  - numba
  - pandas
  - superpunto