name: drop_drying
channels:
  - conda-forge
  - nodefaults
dependencies:
  - libMobility
  - numpy
  - stochasticHydroTools::RigidBodyLight
  - pip
  - pyvista
  - matplotlib
  - scipy
  - pyamg
  - numba
  - plotly
  - pandas
  - pip:
      - icosphere